apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentic-mcp.fullname" . }}
  labels:
    {{- include "agentic-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.stdioPort }}
      targetPort: stdio
      protocol: TCP
      name: stdio
  selector:
    {{- include "agentic-mcp.selectorLabels" . | nindent 4 }}
